import { PlayerTypes } from "../types"
import { PlayerAction } from "../actions/player.actions"
import { PlayerActions } from "../enums";

const initPlayerState  = {
    state:{
        isAnimating:false
    },
    currentAction:PlayerActions.STANCE,
    lives:1,
    velocity:{
        current:10
    },
    isHaveGun:false,
    currentFramesOfGun:[],
    currentFrameOfGun:{
        height:0,
        width:0,
        translateX:0,
        translateY:0
    },
    currentFrame:{
        height:0,
        width:0,
        translateX:0,
        translateY:0
    },
    currentFrames:[],
    stanceFrames:[
        {
            id:1,
            width:30,
            height:33,
            translateX:300,
            translateY:355
        }
    ],
    crouchFrames:[
          {
            id:1,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        }
    ],
    moveFrames:[
        {
            id:1,
            width:30,
            height:33,
            translateX:400,
            translateY:355
        },{
            id:2,
            width:30,
            height:33,
            translateX:500,
            translateY:355
        },{
            id:3,
            width:30,
            height:33,
            translateX:600,
            translateY:355
        }
    ],
    dieFrames:[
         {
            id:1,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        }
    ],
    jumpFrames:[
                {
            id:1,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:2,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:3,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:4,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:5,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        }
    ],
    shootFrames:[
        {
            id:1,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:2,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:3,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:4,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:5,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },
    ],
    blowFrames:[
        {
            id:1,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:2,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        },{
            id:3,
            height:0,
            width:0,
            translateX:0,
            translateY:0
        }
    ]
}


export default function(state = initPlayerState,action:PlayerAction){
    switch(action.type){
        case PlayerTypes.SET_PLAYER_FRAME:
            return{
                ...state,
                currentFrame:action.currentFrame
            }
        default:
            return state
    }
}