import { PlayerTypes } from "../types"
import { PlayerAction } from "../actions/player.actions"
import { PlayerActions } from "../enums";
import {translate} from "@shopify/react-native-skia";

const initPlayerState  = {
    state:{
        isAnimating:false,
        isJumping:false
    },
    currentAction:PlayerActions.STANCE,
    lives:1,
    velocity:{
        current:1
    },
    accX:{
        current:1
    },
    isHaveGun:false,
    translateY:355,
    currentFramesOfGun:[],
    currentFrameOfGun:{
        height:0,
        width:0,
        translateX:0,
        translateY:0
    },
    currentFrame:{
        height:0,
        width:0,
        translateX:0,
    },
    currentFrames:[],
    stanceFrames:[
        {
            id:1,
            width:30,
            height:33,
            translateX:300,
        }
    ],
    crouchFrames:[
           {
            id:1,
            width:30,
            height:33,
            translateX:300,
        }
    ],
    moveFrames:[
        {
            id:1,
            width:30,
            height:33,
            translateX:400,
        },{
             id:1,
            width:30,
            height:33,
            translateX:400,
        },{
            id:1,
            width:30,
            height:33,
            translateX:400,
        }
    ],
    dieFrames:[
         {
            id:1,
            width:30,
            height:33,
            translateX:300,
        }
    ],
    jumpFrames:[
        {
            id:1,
            width:30,
            height:33,
            translateX:400,
        },{
            id:2,
            width:30,
            height:33,
            translateX:400,
        },{
            id:3,
            width:30,
            height:33,
            translateX:400,
        },{
            id:4,
            width:30,
            height:33,
            translateX:400,
        },{
            id:5,
            width:30,
            height:33,
            translateX:400,
        }
    ],
    shootFrames:[
        {
            id:1,
            height:0,
            width:0,
            translateX:0,
        },{
            id:2,
            height:0,
            width:0,
            translateX:0,
        },{
            id:3,
            height:0,
            width:0,
            translateX:0,
        },{
            id:4,
            height:0,
            width:0,
            translateX:0,
        },{
            id:5,
            height:0,
            width:0,
            translateX:0,
        },
    ],
    blowFrames:[
        {
            id:1,
            height:0,
            width:0,
            translateX:0,
        },{
            id:2,
            height:0,
            width:0,
            translateX:0,
        },{
            id:3,
            height:0,
            width:0,
            translateX:0,
        }
    ]
}


export default function(state = initPlayerState,action:PlayerAction){
    switch(action.type){
         case PlayerTypes.SET_STATE_IS_JUMPING:
            state.state.isJumping = action.isJumping
            return{
                ...state,
            }
        case PlayerTypes.SET_PLAYER_CURRENT_FRAME:
            return{
                ...state,
                currentFrame:action.currentFrame
            }
        case PlayerTypes.SET_PLAYER_CURRENT_TRANSLATE_Y:
            return{
                ...state,
                translateY:action.translateY
            }
        case PlayerTypes.SET_PLAYER_CURRENT_FRAMES:
            return{
                ...state,
                currentFrames:action.currentFrames
            }
        default:
            return state
    }
}