export enum AppTypes {
    SET_STATE = "SET_STATE",
    DETECT_CONTROLS_COLLISION = "DETECT_CONTROLS_COLLISION",
    SET_LEFT_BUTTON_ACTION = "SET_LEFT_BUTTON_ACTION",
    SET_RIGHT_BUTTON_ACTION = "SET_RIGHT_BUTTON_ACTION"
}

export enum PlayerTypes{
    SET_PLAYER_FRAME = "SET_PLAYER_FRAME",
    SET_PLAYER_CURRENT_FRAMES = 'SET_PLAYER_CURRENT_FRAMES',
    SET_PLAYER_CURRENT_FRAMES_OF_GUN = "SET_PLAYER_CURRENT_FRAMES_OF_GUN",
    JUMP_ACTION = "JUMP",
    MOVE_LEFT_ACTION = "MOVE_LEFT",
    MOVE_RIGHT_ACTION = "MOVE_RIGHT",
    GUN_ACTION = "GUN_ACTION",
    CROUCH_ACTION = "CROUCH_ACTION",
    MAKE_ACTION = "MAKE_ACTION",
    ANIMATE_PLAYER_SPRITE = "ANIMATE_PLAYER_SPRITE",
    ANIMATE_PLAYER_GUN_SPRITE = "ANIMATE_PLAYER_GUN_SPRITE"
}

export enum WorldTypes{
    DETECT_COLLISION = "DETECT_COLLISION",
    MAKE_ACTION = "MAKE_ACTION",
}

