export enum UITypes {
    CONTROLS_LEFT_ACTION = "CONTROLS_LEFT_ACTION",
    CONTROL_RIGHT_ACTION = "CONTROLES_RIGHT_ACTION",
    CONTROLS_JUMP_ACTION = "CONTROLS_JUMP_ACTION",
    CONTROLS_GUN_ACTION = "CONTROLS_GUN_ACTION",
    CONTROLS_CROUCH_ACTION = "CONTROLS_CROUCH_ACTION"
}

export enum PlayerTypes{
    SET_PLAYER_FRAME = "SET_PLAYER_FRAME",
    SET_PLAYER_CURRENT_FRAMES = 'SET_PLAYER_CURRENT_FRAMES',
    SET_PLAYER_CURRENT_FRAMES_OF_GUN = "SET_PLAYER_CURRENT_FRAMES_OF_GUN",
    JUMP_ACTION = "JUMP",
    MOVE_LEFT_ACTION = "MOVE_LEFT",
    MOVE_RIGHT_ACTION = "MOVE_RIGHT",
    GUN_ACTION = "GUN_ACTION",
    CROUCH_ACTION = "CROUCH_ACTION",
    MAKE_ACTION = "MAKE_ACTION",
    ANIMATE_PLAYER_SPRITE = "ANIMATE_PLAYER_SPRITE",
    ANIMATE_PLAYER_GUN_SPRITE = "ANIMATE_PLAYER_GUN_SPRITE"
}

export enum WorldTypes{
    DETECT_COLLISION = "DETECT_COLLISION",
    MAKE_ACTION = "MAKE_ACTION",
}

